version: '3.3'
services:
  web:
    image: nginx:1.16.0-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
  uwsgi:
    build: .
    environment:
      DB_HOST: db
      DB_NAME: cloudfun
      DB_USER: cloud
      DB_PASS: fun
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: cloudfun
      MYSQL_USER: cloud
      MYSQL_PASSWORD: fun
      MYSQL_ROOT_PASSWORD: cloudfun
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
